import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dde1ff",
        "on-primary": "#ffffff",
        "on-surface-variant": "#45464d",
        "secondary-fixed-dim": "#4cd7f6",
        "on-error": "#ffffff",
        "primary-container": "#001453",
        "on-secondary-container": "#006172",
        "tertiary": "#000000",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "secondary-fixed": "#acedff",
        "primary-fixed-dim": "#b8c4ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#3755c3",
        "surface-container": "#e5eeff",
        "on-tertiary-container": "#9863ff",
        "outline": "#76777d",
        "on-tertiary-fixed-variant": "#5a00c6",
        "on-primary-fixed": "#001453",
        "surface-container-high": "#dce9ff",
        "outline-variant": "#c6c6cd",
        "on-tertiary-fixed": "#25005a",
        "tertiary-container": "#25005a",
        "tertiary-fixed": "#eaddff",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#607cec",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#d2bbff",
        "surface-container-highest": "#d3e4fe",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#004e5c",
        "secondary-container": "#57dffe",
        "surface-dim": "#cbdbf5",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed": "#001f26",
        "inverse-primary": "#b8c4ff",
        "on-surface": "#0b1c30",
        "inverse-surface": "#213145",
        "on-primary-fixed-variant": "#173bab",
        "surface": "#f8f9ff",
        "secondary": "#00687a",
        "on-background": "#0b1c30"
      },
      fontFamily: {
        "headline": ["var(--font-manrope)", "sans-serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
};
export default config;
